CarritoCompras/CarritoCompras/Models/Carrito.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarritoCompras.Models
{
    public class Carrito
    {
        private const string completarObligatorio = "Falta completar {0} , Obligatorio";
        [Required(ErrorMessage = completarObligatorio)]

        public Guid CarritoId { get; set; }
        [Required(ErrorMessage = completarObligatorio)]

        [ForeignKey(nameof(Cliente))]
        public Guid ClienteId { get; set; }
        public Cliente Cliente { get; set; }

        [Required(ErrorMessage = completarObligatorio)]
        public bool Activo { get; set; }

        public List<CarritoItem> CarritosItems { get; set; }

        [Required(ErrorMessage = completarObligatorio)]
        public double Subtotal { get; set; }

    }
}

CarritoCompras/CarritoCompras/Controllers/CarritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarritoCompras.Data;
using CarritoCompras.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarritoCompras.Controllers
{
    public class CarritosController : Controller
    {
        private readonly CarritoComprasContext _context;

        public CarritosController(CarritoComprasContext context)
        {
            _context = context;
        }

        // GET: Carritos
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Index()
        {
            var carritoComprasContext = _context.Carrito.Include(c => c.Cliente);
            return View(await carritoComprasContext.ToListAsync());
        }

        // GET: Carritos
        [Authorize(Roles = nameof(Rol.Cliente))]
        public async Task<IActionResult> CarritoCliente(Guid Id)
        {            
            var carrito = _context.Carrito.Include(n => n.CarritosItems)
                                            .ThenInclude(ci => ci.Producto)
                                          .Include(c => c.Cliente)
                                          .FirstOrDefaultAsync(n => n.ClienteId == Id && n.Activo);
            return View(await carrito);
        }



        // GET: Carritos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito
                .Include(c => c.Cliente)
                .FirstOrDefaultAsync(m => m.CarritoId == id);
            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        // GET: Carritos/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Apellido");
            return View();
        }

        // POST: Carritos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("CarritoId,ClienteId,Activo,Subtotal")] Carrito carrito)
        {
            if (ModelState.IsValid)
            {
                carrito.CarritoId = Guid.NewGuid();
                _context.Add(carrito);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Apellido", carrito.ClienteId);
            return View(carrito);
        }

        // POST: Carritos/Agregar/5
        // Agrega un CarritoItem al Carrito
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Agregar(Producto producto, int Cantidad)
        {
            if(Cantidad >= 1)
            {
                var usuarioId = Guid.Parse(User.FindFirst("IdDeUsuario").Value);

                var carrito = await _context.Carrito.FirstOrDefaultAsync(p => p.ClienteId == usuarioId && p.Activo);

                var carritoItem = new CarritoItem();
                carritoItem.Cantidad = Cantidad;
                carritoItem.ProductoId = producto.ProductoId;
                carritoItem.CarritoId = carrito.CarritoId;

                _context.CarritoItem.Add(carritoItem);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(CarritoCliente), new { id = carrito.ClienteId });
            }
            TempData["error"] = "Ingrese 1 o más productos";
            return RedirectToAction("Agregar", "Productos", new { id = producto.ProductoId});
        }

        // GET: Carritos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito.FindAsync(id);
            if (carrito == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Apellido", carrito.ClienteId);
            return View(carrito);
        }

        // POST: Carritos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id, [Bind("CarritoId,ClienteId,Activo,Subtotal")] Carrito carrito)
        {
            if (id != carrito.CarritoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carrito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarritoExists(carrito.CarritoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "Id", "Apellido", carrito.ClienteId);
            return View(carrito);
        }

        // GET: Carritos/Edit/5
        [Authorize]
        public async Task<IActionResult> EditarItem(Guid? id, int Cantidad)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carritoItem = await _context.CarritoItem
                .Include(n => n.Producto)
                //.ThenInclude(n => n.Categoria)
                .Include(n => n.Carrito)
                .FirstOrDefaultAsync(n => n.CarritoItemId == id);
            if (carritoItem == null)
            {
                return NotFound();
            }
            ViewData["Cantidad"] = Cantidad;
            return View(carritoItem);
        }

        // POST: Carritos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> EditarItem(Guid id, CarritoItem carritoItem)
        {
            if (id != carritoItem.CarritoItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carritoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarritoExists(carritoItem.CarritoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                var carrito = await _context.Carrito
                    .FirstOrDefaultAsync(m => m.CarritoId == carritoItem.CarritoId);
                return RedirectToAction(nameof(CarritoCliente), new { id = carrito.ClienteId });
            }

            return View(id);
        }

        // GET: Carritos/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carrito = await _context.Carrito
                .Include(c => c.Cliente)
                .FirstOrDefaultAsync(m => m.CarritoId == id);
            if (carrito == null)
            {
                return NotFound();
            }

            return View(carrito);
        }

        // POST: Carritos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var carrito = await _context.Carrito.FindAsync(id);
            _context.Carrito.Remove(carrito);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Carritos/Delete/5
        [Authorize]
        public async Task<IActionResult> RemoveItem(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carritoItem = await _context.CarritoItem
                .Include(c => c.Producto)
                .Include(c => c.Carrito)
                .FirstOrDefaultAsync(m => m.CarritoItemId == id);
            if (carritoItem == null)
            {
                return NotFound();
            }

            return View(carritoItem);
        }

        // POST: Carritos/Delete/5
        [HttpPost, ActionName("RemoveItem")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> RemoveItem1(Guid id)
        {
            var carritoItem = await _context.CarritoItem
                  .FirstOrDefaultAsync(m => m.CarritoItemId == id);
            var carrito = await _context.Carrito
                .FirstOrDefaultAsync(m => m.CarritoId == carritoItem.CarritoId);
            _context.CarritoItem.Remove(carritoItem);
            await _context.SaveChangesAsync();

CarritoCompras/CarritoCompras/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarritoCompras.Data;
using CarritoCompras.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarritoCompras.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly CarritoComprasContext _context;

        public CategoriasController(CarritoComprasContext context)
        {
            _context = context;
        }

        // GET: Categorias
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categoria.ToListAsync());
        }

        // GET: Categorias
        [Authorize]
        public async Task<IActionResult> Seleccionar()
        {
            return View(await _context.Categoria.ToListAsync());
        }

        // GET: Categorias/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.CategoriaId == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        [Authorize(Roles = nameof(Rol.Administrador))]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Create([Bind("CategoriaId,Nombre,Descripcion")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoria.CategoriaId = Guid.NewGuid();
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Edit(Guid id, [Bind("CategoriaId,Nombre,Descripcion")] Categoria categoria)
        {
            if (id != categoria.CategoriaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.CategoriaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.CategoriaId == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(Rol.Administrador))]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var categoria = await _context.Categoria.FindAsync(id);
            _context.Categoria.Remove(categoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(Guid id)
        {
            return _context.Categoria.Any(e => e.CategoriaId == id);
        }
    }
}

CarritoCompras/CarritoCompras/Views/Carritos/CarritoCliente.cshtml
@model CarritoCompras.Models.Carrito

@{
    ViewData["Title"] = "Carrito";
}

<h1>Carrito</h1>
<p>
    <a asp-action="Seleccionar" asp-controller="Categorias">Agregar Productos</a>
</p>
<p>
    <a asp-action="Vaciar" asp-controller="Carritos" asp-route-id="@Model.CarritoId">Vaciar Carrito</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Precio Unitario
            </th>
            <th>
                Subtotal
            </th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CarritosItems)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producto.PrecioVigente)
            </td>
            <td>
                @{var x = item.Cantidad * item.Producto.PrecioVigente; }
                @x.ToString()
            </td>
            <td>
                <a asp-action="EditarItem" asp-route-id="@item.CarritoItemId">Editar</a> | <a asp-action="RemoveItem" asp-route-id="@item.CarritoItemId">Borrar</a> 
            </td>
        </tr>
        }
    </tbody>
</table>
<a asp-action="SucursalCompra" asp-controller="Sucursales" asp-route-id="@Model.CarritoId" class="btn-primary">Comprar</a>

CarritoCompras/CarritoCompras/Views/Carritos/Create.cshtml
@model CarritoCompras.Models.Carrito

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carrito</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class ="form-control" asp-items="ViewBag.ClienteId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/CarritoCompras/Views/Carritos/Delete.cshtml
@model CarritoCompras.Models.Carrito

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Apellido)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarritoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarritoCompras/CarritoCompras/Views/Carritos/Details.cshtml
@model CarritoCompras.Models.Carrito

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carrito</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CarritoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarritoCompras/CarritoCompras/Views/Carritos/Edit.cshtml
@model CarritoCompras.Models.Carrito

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carrito</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarritoId" />
            <div class="form-group">
                <label asp-for="ClienteId" class="control-label"></label>
                <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Activo" /> @Html.DisplayNameFor(model => model.Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/CarritoCompras/Views/Carritos/EditarItem.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Editar Producto";
}

<h1>Editar Producto</h1>

<h4>CarritoItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarritoItemId" />
            <input type="hidden" asp-for="CarritoId" />
            <input type="hidden" asp-for="ProductoId" />
            @Model.Producto.Nombre
            <br />
            @Model.Producto.Descripcion
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarritoCompras/CarritoCompras/Views/Carritos/Index.cshtml
@model IEnumerable<CarritoCompras.Models.Carrito>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtotal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subtotal)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CarritoId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CarritoId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CarritoId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CarritoCompras/CarritoCompras/Views/Carritos/RemoveItem.cshtml
@model CarritoCompras.Models.CarritoItem

@{
    ViewData["Title"] = "Borrar Item";
}

<h1>Borrar</h1>

<h3>Está seguro en borrar el Item?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producto.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producto.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producto.PrecioVigente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producto.PrecioVigente)
        </dd>
        <dt class="col-sm-2">
            Subtotal
        </dt>
        <dd class="col-sm-10">
            @{var x = Model.Cantidad * Model.Producto.PrecioVigente; }
            @x.ToString()
        </dd>
    </dl>    

    <form asp-action="RemoveItem">
        <input type="hidden" asp-for="CarritoItemId" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="CarritoCliente" asp-route-id="@Model.Carrito.ClienteId">Volver</a>
    </form>
</div>